import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, setPersistence, browserLocalPersistence, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getFirestore, collection, doc, getDocs, onSnapshot, setDoc, writeBatch, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const config={apiKey:"AIzaSyB7fo20WlKpoySHDBdtjilOqVYRAI8OvKM",authDomain:"su-mega.firebaseapp.com",projectId:"su-mega",storageBucket:"su-mega.firebasestorage.app",messagingSenderId:"747588237835",appId:"1:747588237835:web:b5cc26c6971ca37cb3a50e"};
const app=initializeApp(config,"su-mega-cloud-v2");
const auth=getAuth(app);
const db=getFirestore(app);
const STATUS_KEY="su-mega-c2-status-v1";
const CONTEST_KEY="su-mega-c2-contests-v1";
const VALID=new Set(["pendente","registrado","apostado"]);
let user=null, stopStatus=null, stopContests=null, applying=false, startedUid=null;

function parse(raw,fallback){try{return JSON.parse(raw??"")}catch{return fallback}}
function localStatuses(){const p=parse(localStorage.getItem(STATUS_KEY),{});const s=p?.statuses||p||{};const out={};for(const [id,v] of Object.entries(s))if(VALID.has(v))out[id]=v;return out}
function localContests(){const v=parse(localStorage.getItem(CONTEST_KEY),[]);return Array.isArray(v)?v:[]}
function state(kind,text){const b=document.getElementById("su-cloud-status");const t=document.getElementById("su-cloud-status-text");if(b)b.dataset.state=kind;if(t)t.textContent=text}
function toast(text){globalThis.SUMegaApp?.announce?.(text)}

function ui(){
 if(document.getElementById("su-cloud-root"))return;
 const style=document.createElement("style");style.textContent=`#su-cloud-root{position:fixed;right:14px;bottom:14px;z-index:9998}.su-cloud-button{border:0;border-radius:999px;padding:11px 15px;background:#0d5f3d;color:#fff;font-weight:800;box-shadow:0 8px 28px #0003}.su-cloud-gate{position:fixed;inset:0;z-index:10000;background:#062f20f2;display:grid;place-items:center;padding:24px}.su-cloud-gate[hidden]{display:none}.su-cloud-card{width:min(430px,100%);background:#fff;border-radius:24px;padding:26px;color:#17202a}.su-cloud-card label{display:grid;gap:7px;margin-top:15px;font-weight:700}.su-cloud-card input{font:inherit;padding:13px;border:1px solid #cbd5e1;border-radius:12px}.su-cloud-card button{font:inherit;font-weight:800;border-radius:12px;border:0;padding:12px 15px}.primary{background:#16834f;color:#fff;width:100%;margin-top:18px}.su-cloud-error{color:#b91c1c;font-weight:700}.su-cloud-user{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #ddd;margin-top:14px;padding-top:14px}.su-cloud-user[hidden]{display:none}`;document.head.appendChild(style);
 const root=document.createElement("div");root.id="su-cloud-root";root.innerHTML=`<button id="su-cloud-status" class="su-cloud-button" data-state="offline"><span id="su-cloud-status-text">Nuvem desconectada</span></button>`;document.body.appendChild(root);
 const gate=document.createElement("div");gate.id="su-cloud-gate";gate.className="su-cloud-gate";gate.innerHTML=`<div class="su-cloud-card"><p style="color:#16834f;font-weight:900;margin:0">SU MEGA CLOUD</p><h2>Entrar para sincronizar</h2><p>Use o mesmo e-mail e senha no iPhone e no iPad.</p><form id="su-cloud-login-form"><label>E-mail<input id="su-cloud-email" type="email" autocomplete="username" required></label><label>Senha<input id="su-cloud-password" type="password" autocomplete="current-password" required></label><p id="su-cloud-error" class="su-cloud-error"></p><button class="primary" type="submit">Entrar</button></form><div id="su-cloud-user" class="su-cloud-user" hidden><span id="su-cloud-user-email"></span><button id="su-cloud-logout">Sair</button></div></div>`;document.body.appendChild(gate);
 document.getElementById("su-cloud-status").onclick=()=>gate.hidden=false;
 document.getElementById("su-cloud-login-form").onsubmit=async e=>{e.preventDefault();const err=document.getElementById("su-cloud-error");err.textContent="";state("saving","Entrando…");try{await setPersistence(auth,browserLocalPersistence);await signInWithEmailAndPassword(auth,document.getElementById("su-cloud-email").value.trim(),document.getElementById("su-cloud-password").value)}catch(x){console.error(x);err.textContent=`Não foi possível entrar (${x.code||"erro"}).`;state("error","Falha no login")}};
 document.getElementById("su-cloud-logout").onclick=()=>signOut(auth);
 window.addEventListener("offline",()=>state("offline","Offline • alterações em espera"));
 window.addEventListener("online",()=>user&&state("saving","Reconectando…"));
}
function authUi(u){const g=document.getElementById("su-cloud-gate"),f=document.getElementById("su-cloud-login-form"),box=document.getElementById("su-cloud-user"),mail=document.getElementById("su-cloud-user-email");if(u){g.hidden=true;f.hidden=true;box.hidden=false;mail.textContent=u.email||"Usuário conectado"}else{g.hidden=false;f.hidden=false;box.hidden=true;mail.textContent=""}}

async function uploadStatuses(statuses){if(!user)return;const entries=Object.entries(statuses);for(let i=0;i<entries.length;i+=400){const batch=writeBatch(db);for(const [id,status] of entries.slice(i,i+400))batch.set(doc(db,"users",user.uid,"gameStatuses",id),{status,updatedAt:serverTimestamp(),wallet:"C2"},{merge:true});await batch.commit()}}
async function uploadContests(contests){if(!user)return;for(let i=0;i<contests.length;i+=400){const batch=writeBatch(db);for(const c of contests.slice(i,i+400))batch.set(doc(db,"users",user.uid,"contests",String(Number(c.number))),{...c,number:Number(c.number),updatedAtCloud:serverTimestamp(),wallet:"C2"},{merge:true});await batch.commit()}}
function applyStatuses(snap){const current=localStatuses();snap.forEach(d=>{const v=d.data()?.status;if(VALID.has(v))current[d.id]=v});const payload={app:"SU Mega",wallet:"C2",schema:2,savedAt:new Date().toISOString(),statuses:current};applying=true;localStorage.setItem(STATUS_KEY,JSON.stringify(payload));applying=false;window.dispatchEvent(new StorageEvent("storage",{key:STATUS_KEY,newValue:JSON.stringify(payload)}))}
function applyContests(snap){const list=[];snap.forEach(d=>{const x=d.data();list.push({number:Number(x.number??d.id),date:String(x.date||""),numbers:Array.isArray(x.numbers)?x.numbers.map(Number).sort((a,b)=>a-b):[],source:String(x.source||""),notes:String(x.notes||""),createdAt:String(x.createdAt||""),updatedAt:String(x.updatedAt||"")})});list.sort((a,b)=>b.number-a.number);applying=true;if(!globalThis.SUMegaContests?.importData?.(list,true))localStorage.setItem(CONTEST_KEY,JSON.stringify(list));applying=false}

const nativeSet=Storage.prototype.setItem;
Storage.prototype.setItem=function(k,v){const old=this.getItem(k);nativeSet.call(this,k,v);if(this===localStorage&&!applying&&old!==String(v)&&user){if(k===STATUS_KEY)uploadStatuses(localStatuses()).then(()=>state("synced","Sincronizado")).catch(e=>{console.error(e);state("error","Falha ao salvar")});if(k===CONTEST_KEY)uploadContests(localContests()).then(()=>state("synced","Sincronizado")).catch(e=>{console.error(e);state("error","Falha ao salvar concursos")})}};

async function start(u){if(startedUid===u.uid)return;startedUid=u.uid;state("saving","Preparando sincronização…");const sr=collection(db,"users",u.uid,"gameStatuses"),cr=collection(db,"users",u.uid,"contests");const [rs,rc]=await Promise.all([getDocs(sr),getDocs(cr)]);if(rs.empty){const nonDefault=Object.fromEntries(Object.entries(localStatuses()).filter(([,v])=>v!=="pendente"));if(Object.keys(nonDefault).length)await uploadStatuses(nonDefault)}if(rc.empty&&localContests().length)await uploadContests(localContests());stopStatus?.();stopContests?.();stopStatus=onSnapshot(sr,s=>{applyStatuses(s);state(navigator.onLine?"synced":"offline",navigator.onLine?"Sincronizado":"Offline • cache local")},e=>{console.error(e);state("error",`Erro status: ${e.code||""}`)});stopContests=onSnapshot(cr,s=>{applyContests(s);state(navigator.onLine?"synced":"offline",navigator.onLine?"Sincronizado":"Offline • cache local")},e=>{console.error(e);state("error",`Erro concursos: ${e.code||""}`)})}

ui();state("saving","Verificando login…");onAuthStateChanged(auth,async u=>{user=u;authUi(u);if(!u){startedUid=null;stopStatus?.();stopContests?.();state("offline","Entre para sincronizar");return}try{await start(u);document.getElementById("su-cloud-gate").hidden=true}catch(e){console.error(e);state("error",`Erro: ${e.code||e.message||"nuvem"}`);const m=document.getElementById("su-cloud-error");if(m)m.textContent=`Falha ao acessar o Firestore: ${e.code||e.message||"erro desconhecido"}`;document.getElementById("su-cloud-gate").hidden=false}});