(() => {
"use strict";
const C={app:'SU Mega',lockKey:'su-mega-c2-contest-locks-v1',betsKey:'su-mega-c2-contest-bets-v1',statusKey:'su-mega-c2-status-v1',resultKey:'su-mega-c2-contests-v1',contestsApi:'SUMegaContests',styleId:'su-mega-contest-lock-style',ids:{root:'su-contest-bets',number:'su-bet-contest',summary:'su-bet-summary',history:'su-bet-history',save:'su-save-contest-bets',close:'su-close-contest-bets',delete:'su-delete-contest-bets',fields:['su-bet-type','su-bet-special-name','su-bet-price','su-bet-release']}};
const LOCK_KEY=C.lockKey,BETS_KEY=C.betsKey,STATUS_KEY=C.statusKey,RESULT_KEY=C.resultKey;
let locked=new Set(),busy=false,renderQueued=false;
function parse(raw,fallback){try{return JSON.parse(raw??"")}catch{return fallback}}
function now(){return new Date().toISOString()}
function valid(v){const n=Number(v);return Number.isInteger(n)&&n>0?n:null}
function loadBets(){const v=parse(localStorage.getItem(BETS_KEY),{});return v&&typeof v==="object"&&!Array.isArray(v)?v:{}}
function saveBets(data){try{localStorage.setItem(BETS_KEY,JSON.stringify(data));window.dispatchEvent(new CustomEvent("su:contest-bets-updated"));return true}catch(e){console.error(C.app+" bloqueio de concursos:",e);return false}}
function loadLocks(){const v=parse(localStorage.getItem(LOCK_KEY),{}),set=new Set();for(const k of Object.keys(v&&typeof v==="object"?v:{})){const n=valid(k);if(n)set.add(n)}return set}
function saveLocks(){const out={};for(const n of locked)out[String(n)]={lockedAt:now()};localStorage.setItem(LOCK_KEY,JSON.stringify(out))}
function statusPayload(){const raw=parse(localStorage.getItem(STATUS_KEY),{}),statuses=raw?.statuses||raw||{};return{raw,statuses:{...statuses}}}
function persistStatuses(raw,statuses){const payload=raw&&typeof raw==="object"&&raw.statuses?{...raw,savedAt:now(),statuses}:{app:C.app,wallet:"C2",schema:2,savedAt:now(),statuses};const value=JSON.stringify(payload);localStorage.setItem(STATUS_KEY,value);window.dispatchEvent(new StorageEvent("storage",{key:STATUS_KEY,newValue:value}))}
function localOfficialNumbers(){const set=new Set();try{const api=globalThis[C.contestsApi],list=api?.exportData?.()||parse(localStorage.getItem(RESULT_KEY),[]);if(Array.isArray(list))for(const row of list){const n=valid(row?.number);if(n)set.add(n)}}catch{}return set}
async function fetchNumbers(url){const response=await fetch(url,{cache:"no-store",headers:{Accept:"application/json"}});if(!response.ok)throw Error("HTTP "+response.status);const payload=await response.json(),source=Array.isArray(payload)?payload:(payload?.results||[payload]),set=new Set();for(const row of source||[]){const n=valid(row?.number??row?.numero);if(n)set.add(n)}return set}
function concludeLocked(){const bets=loadBets(),{raw,statuses}=statusPayload();let betsChanged=false,statusChanged=false;for(const n of locked){const row=bets[String(n)];if(!row||row.status==="concluido")continue;row.status="concluido";row.concludedAt=row.concludedAt||now();row.updatedAt=now();bets[String(n)]=row;betsChanged=true;const destination=row.releaseStatus==="registrado"?"registrado":"pendente";for(const id of Array.isArray(row.gameIds)?row.gameIds:[]){const key=String(id);if(statuses[key]==="apostado"){statuses[key]=destination;statusChanged=true}}}if(betsChanged)saveBets(bets);if(statusChanged)persistStatuses(raw,statuses);if(betsChanged||statusChanged)setTimeout(()=>location.reload(),700)}
function addOfficial(numbers){const bets=loadBets(),relevant=new Set(Object.keys(bets).map(valid).filter(Boolean));let changed=false;for(const n of numbers)if(relevant.has(n)&&!locked.has(n)){locked.add(n);changed=true}if(changed){saveLocks();concludeLocked();queueRender()}}
async function refresh({archive=false}={}){if(busy)return;busy=true;try{const all=localOfficialNumbers();try{(await fetchNumbers("./data/ultimo-concurso.json")).forEach(n=>all.add(n))}catch{}if(archive)try{(await fetchNumbers("./data/concursos-oficiais.json")).forEach(n=>all.add(n))}catch{}addOfficial(all)}finally{busy=false}}
function selected(){return valid(document.getElementById(C.ids.number)?.value)}
function isLocked(n){return Boolean(n&&locked.has(Number(n)))}
function queueRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;render()})}
function markDisabled(element,on,fallback=false){if(!element)return;if(on){element.disabled=true;element.dataset.suLockDisabled="1"}else if(element.dataset.suLockDisabled){delete element.dataset.suLockDisabled;element.disabled=fallback}}
function render(){const root=document.getElementById(C.ids.root);if(!root)return;const n=selected(),row=n?loadBets()[String(n)]:null,on=isLocked(n);const summary=document.getElementById(C.ids.summary);if(summary){let badge=summary.querySelector(".su-official-lock");if(on&&!badge){badge=document.createElement("span");badge.className="su-official-lock";badge.textContent="Resultado publicado • bloqueado";summary.append(document.createElement("br"),badge)}if(!on&&badge)badge.remove()}markDisabled(document.getElementById(C.ids.save),on,false);markDisabled(document.getElementById(C.ids.close),on,!row||row.status==="concluido");markDisabled(document.getElementById(C.ids.delete),on,!row);for(const id of C.ids.fields)markDisabled(document.getElementById(id),on,false);const history=document.getElementById(C.ids.history);history?.querySelectorAll("button[data-contest]").forEach(button=>{const contest=valid(button.dataset.contest),lockedRow=isLocked(contest);let tag=button.querySelector(".su-official-lock-history");if(lockedRow&&!tag){tag=document.createElement("small");tag.className="su-official-lock-history";tag.textContent="Resultado publicado • bloqueado";button.appendChild(tag)}if(!lockedRow&&tag)tag.remove();button.classList.toggle("su-official-locked-row",lockedRow)})}
function install(){const root=document.getElementById(C.ids.root);if(!root||document.getElementById(C.styleId))return false;locked=loadLocks();const style=document.createElement("style");style.id=C.styleId;style.textContent=`.su-official-lock{display:inline-block;margin-top:7px;padding:5px 8px;border-radius:999px;background:#fbe8ea;color:#a51d2d;font-size:.78rem;font-weight:900}.su-official-lock-history{display:block;margin-top:5px;color:#a51d2d;font-size:.78rem;font-weight:900}.su-official-locked-row{border-color:#e8aab2!important;background:#fff8f9!important}`;document.head.appendChild(style);document.addEventListener("click",event=>{const button=event.target.closest?.(`#${C.ids.save},#${C.ids.close},#${C.ids.delete}`);if(!button||!isLocked(selected()))return;event.preventDefault();event.stopImmediatePropagation();alert("O resultado oficial deste concurso já foi publicado. O registro está bloqueado e não pode mais ser alterado.")},true);document.getElementById(C.ids.number)?.addEventListener("input",queueRender);document.getElementById(C.ids.history)?.addEventListener("click",()=>setTimeout(queueRender,0));new MutationObserver(queueRender).observe(root,{subtree:true,childList:true,characterData:true});window.addEventListener("su:contest-bets-cloud-updated",queueRender);window.addEventListener("focus",()=>refresh());document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")refresh()});setInterval(()=>addOfficial(localOfficialNumbers()),3000);setInterval(()=>refresh(),5*60*1000);setTimeout(()=>{refresh({archive:true});queueRender()},700);return true}
if(!install()){let attempts=0,timer=setInterval(()=>{if(install()||++attempts>=60)clearInterval(timer)},250)}
})();