const CACHE_NAME="su-mega-c2-cloud-v13";
const APP_ASSETS=["./","./index.html","./styles.css","./contests.css","./core.js","./contest-core.js","./contests.js","./app.js","./official-results.js","./pwa-install-compat.js","./cloud-sync-v2.js","./account-panel.js","./ecosystem-ui.js?v=7","./prize-analysis.js?v=2","./contest-bets.js?v=1","./ui-polish.js?v=1","./data/games-01.js","./data/games-02.js","./data/games-03.js","./data/games-04.js","./data/games-05.js","./data/games-06.js","./data/games-07.js","./data/games-08.js","./data/games-09.js","./data/games-10.js","./data/ultimo-concurso.json","./data/concursos-oficiais.json","./manifest.json","./assets/icons/icon.svg"];
const LOADER="\n;/* SU_CLOUD_LOADER */import('./pwa-install-compat.js').then(()=>import('./cloud-sync-v2.js')).then(()=>import('./account-panel.js')).then(()=>import('./ecosystem-ui.js?v=7')).then(()=>import('./prize-analysis.js?v=2')).then(()=>import('./contest-bets.js?v=1')).then(()=>import('./ui-polish.js?v=1')).catch(error=>console.error('SU Mega Cloud:',error));\n";
self.addEventListener("install",event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(APP_ASSETS)));self.skipWaiting()});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("su-mega-")&&key!==CACHE_NAME).map(key=>caches.delete(key)))));self.clients.claim()});
async function updateCache(request){try{const response=await fetch(request,{cache:"no-store"});if(response.ok){const cache=await caches.open(CACHE_NAME);await cache.put(request,response.clone())}return response}catch{return null}}
async function officialResultsFast(request,event){const cache=await caches.open(CACHE_NAME);let response=await cache.match(request);if(response){event.waitUntil(updateCache(request));}else{response=await updateCache(request)}if(!response)return new Response(LOADER,{headers:{"Content-Type":"application/javascript; charset=utf-8"}});const source=await response.text();return new Response(source.includes("SU_CLOUD_LOADER")?source:source+LOADER,{status:200,headers:{"Content-Type":"application/javascript; charset=utf-8","Cache-Control":"no-store"}})}
async function navigationFast(request,event){const cache=await caches.open(CACHE_NAME);const cached=await cache.match("./index.html");const refresh=fetch(request,{cache:"no-store"}).then(response=>{if(response.ok)cache.put("./index.html",response.clone());return response}).catch(()=>null);if(cached){event.waitUntil(refresh);return cached}return(await refresh)||new Response("Aplicativo indisponível",{status:503})}
async function networkFirst(request){const cache=await caches.open(CACHE_NAME);try{const response=await fetch(request,{cache:"no-store"});if(response.ok)await cache.put(request,response.clone());return response}catch{return(await cache.match(request))||new Response("Sem conexão",{status:503})}}
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET")return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith("/official-results.js")){event.respondWith(officialResultsFast(request,event));return}if(url.pathname.endsWith("/data/ultimo-concurso.json")||url.pathname.endsWith("/data/concursos-oficiais.json")){event.respondWith(networkFirst(request));return}if(request.mode==="navigate"){event.respondWith(navigationFast(request,event));return}event.respondWith(caches.match(request).then(cached=>{if(cached){event.waitUntil(updateCache(request));return cached}return updateCache(request).then(response=>response||new Response("Recurso indisponível",{status:503}))}))});